---
title: "Task Day 2"
author: "Javier Patron"
date: "2022-08-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library("palmerpenguins")


```

##Find the derivatrive expression and slope of exercise A
$f(x) = x ^ 2 $
$f(x) = 3$

```{r}
exp_A <- expression(x ^ 2)
deriv_result_A <- deriv(exp_A, "x")
deriv_result_A

x <- 3
m_result_A <- eval(deriv_result_A)
m_result_A

```

##Find the derivatrive expression and slope of exercise B

$P(a) = 2(3a + 2)^4 - 5$
$P(a) = 1.2$

```{r}
exp_b = expression(2 * (3 * a + 2)^4 - 5)
deriv_B <- deriv(exp_b, "a")
deriv_B

a <- 1.2
m_result_B <- eval(deriv_B)
m_result_B

```

##Find the derivatrive expression and slope of exercise C

$g(t) = (-4t) / (t2+1)^3

g(t) = 0

```{r}
exp_c = expression((-4 * t) / (t ^ 2 + 1 )^3)
deriv_c = deriv(exp_c, "t")
deriv_c

t <- 0
m_result_c <- eval(deriv_c)
m_result_c


```



### Section 4: Make a penguin plot

```{r}

head(penguins)

ggplot(data = penguins, aes(x=bill_length_mm, y=bill_depth_mm)) + 
  geom_point(aes(color = species) ) + 
  labs(x = "Bill Length (mm)", 
       y="Bill Depth (mm)", 
       title = "PenguinsTitles")
            
             
```

###Make a Jitterplot of Flipper Length by Species

```{r}
ggplot(data = penguins, aes(x=species, y = flipper_length_mm)) +
  geom_jitter() + 
  labs(x = "Species", 
       y = "Flipper Length (mm)")
```




